module.exports = ['biology', 'abdomen', 'autotroph', 'atrophy', 'amoeba',
  'bacteria', 'brain', 'biopsy', 'blood', 'bilirubin', 'biomechanics',
  'catabolism', 'chloroplast', 'cytokinesis', 'cytoskeleton', 'chlorophyll',
  'chromosome', 'condensation', 'crispr', 'cytoplasm', 'diffusion', 'fluoride',
  'frenulum', 'formaldehyde', 'fungi', 'genetics', 'gerontology', 'glycogen',
  'heredity', 'heterotroph', 'horticulture', 'hyperplasia', 'hypotonic', 'heterozygous',
  'homologous', 'hydrophobic', 'hypertonic', 'interphase', 'isotonic', 'methanol',
  'monosaccharide', 'mitosis', 'methanol', 'meiosis', 'metamorphosis', 'metastasize',
  'mitochondria', 'molecule', 'muscle', 'mutation', 'nucleotide', 'nephrology',
  'neuroscience', 'nitrogen', 'omnivore', 'organism', 'oncology', 'organelle',
  'osmosis', 'pathology', 'phagocytosis', 'physiology', 'plant', 'prophase',
  'pedigree', 'phenotype', 'placenta', 'population', 'protozoa', 'skeleton',
  'solute', 'solvent', 'spleen', 'sucrose', 'symbiosis', 'solution', 'skin',
  'species', 'substrate', 'taxonomy', 'tissue', 'transcription', 'telophase',
  'thymus', 'thyroid', 'toxicology', 'vacuole', 'vesicle', 'virus', 'vasodilation',
  'zygote'
]